function translate(str){
  if (translate_hash[str]) { return translate_hash[str]; }
  else { return str; }
}
var translate_hash = {
"Language":"Language",
"Language name":"Română",
"Language path":"ro-RO",
"Group":"Grup",
"Component":"Component",
"Default":"Implicit",
"Activation":"Activare",
"Main":"ART ROCKET",
"Components":"Componente",
"Componentov":"Componente",
"Componenta":"Componenta",
"Attributes":"Atribute",
"Clear - auto":"Curăță - auto",
"Materials":"Materiale",
"PVC":"VINYL",
"Plastic":"PLASTIC",
"Chipboard":"CPB",
"Enamel":"ENAMEL",
"Veneer":"VENEER",
"Wood":"WOOD",
"Search material...":"Caută materialul…",
"filter":"filtru",
"Choose a material":"Alege un material",
"Standard materials":"Materiale standard",
"Standard":"Standard",
"Change the edge according to the parameters":"Schimbă marginea conform parametrilor",
"Patina":"Patină",
"Add material":"Adaugă material",
"Delete":"Șterge",
"G_":"Г_",
"M_":"М_",
"Gold":"Gold",
"Silver":"Silver",
"Brown":"Brown",
"Black":"Black",
"Lists":"Liste",
"Model":"Model",
"Accessories/Fasteners":"Accesorii/Fixatori",
"Acc/Fast":"Acc/Fix",
"Sheets":"Foi",
"Linear":"Liniar",
"Operations":"Operațiuni",
"Cost":"Cost",
"Price list":"Listă de prețuri",
"price":"preț",
"Copy the list":"Copiază lista",
"Name":"Nume",
"Total":"Total",
"The volume of modules":"Volumul modulelor",
"Change the name":"Schimbă numele",
"Collapse/expand the list":"Restrânge/Extinde lista",
"Select all the details":"Selectează toate detaliile",
"strip":"fâșie",
"stripes":"fâșii",
"strips":"benzi",
"Edge":"Edge",
"Cutting details":"Detalii de tăiere",
"Exporting a list":"Exportă lista",
"Texture without direction":"Textură fără direcție",
"Directional texture":"Textură direcționată",
"Number of parts":"Număr de piese",
"Total number of parts":"Număr total de piese",
"List of holes":"Listă de găuri",
"Hole":"Gaura",
"Turning in the cutting":"Întoarcere în tăiere",
"Change the part name":"Schimbă numele piesei",
"Select a part":"Selectează o piesă",
"The list is copied to the clipboard":"Lista este copiată în clipboard",
"Frame facades":"Fațade cu ramă",
"The list is copied":"Lista a fost copiată",
"Component Options":"Opțiuni componente",
"Copying library files...":"Copiere fișiere bibliotecă...",
"Price List Editor":"Editor listă de prețuri",
"Select a folder to save the price lists":"Selectează un dosar pentru a salva listele de prețuri",
"Select a folder with price lists":"Selectează un dosar cu liste de prețuri",
"Select the location of the materials folder":"Selectează locația dosarului cu materiale",
"Import Parameters":"Parametrii importului",
"Name prefix":"Prefix nume",
"The supplier":"Furnizorul",
"Article number":"Număr articol",
"Unit":"Unitate",
"Price":"Preț",
"Currency":"Monedă",
"Ratio":"Raport",
"Work":"Lucru",
"Category":"Categorie",
"Add ":"Adaugă ",
" in a library":" în bibliotecă",
"Change ":"Schimbă ",
" in selected products":" în produsele selectate",
"No Components Selected":"Nicio componentă selectată",
"Select one or more components and view their parameters.":"Selectează una sau mai multe componente și vizualizează parametrii acestora.",
"Parameters of nested components":"Parametrii componentelor înglobate",
"The selected components do not have parameters that can be edited at all.":"Componentele selectate nu au parametri care pot fi editați.",
"The component has no parameters that can be edited":"Componenta nu are parametri care pot fi editați",
"Save project":"Salvează proiectul",
"Select Carcass":"Selectează carcasă",
"ScreenShot":"Captură ecran",
"Make":"Creează",
"Save":"Salvează",
"Module Settings":"Setări modul",
"Close all doors":"Închide toate ușile",
"Att Report":"Raport atașament",
"Generate Report":"Generează raport",
"Drawing":"Desen",
"Error":"Eroare",
"Licence error":"Eroare licență",
"Select nested panels":"Selectează panouri înglobate",
"Click to select objects. Shift = Add/Subtract. Ctrl = Add.":"Apasă pentru a selecta obiecte. Shift = Adaugă/Scade. Ctrl = Adaugă.",
"Interact with Dynamic Components":"Interacționează cu Componentele Dinamice",
"One click at a time changes the interaction objects":"Un clic pe rând schimbă obiectele de interacțiune",
"Throw_to_face":"Aruncă pe față",
"Update the plugin and library":"Actualizează pluginul și biblioteca",
"Update":"Actualizare",
"Update Parameters":"Actualizare parametri",
"Plugin from the server":"Plugin de pe server",
"Plugin from a file":"Plugin din fișier",
"Library from folder":"Bibliotecă din dosar",
"Library from the server":"Bibliotecă de pe server",
"There is an update for the plugin":"Există o actualizare pentru plugin",
"A new version of the plugin is available":"O nouă versiune a pluginului este disponibilă",
"To continue without updating, click any tab":"Pentru a continua fără actualizare, apasă pe orice filă",
"What's new?":"Ce este nou?",
"Update the plugin":"Actualizează pluginul",
"Update the plugin is successfully":"Actualizarea pluginului a reușit",
"Library update completed":"Actualizarea bibliotecii completată",
"Restart":"Repornește",
"Update the library":"Actualizează biblioteca",
"Specify the location of the archive with the plugin files":"Specificați locația arhivei cu fișierele pluginului",
"Select the su_furniture folder":"Selectează dosarul su_furniture",
"Select a folder":"Selectează un dosar",
"Copying Library files":"Copiere fișiere bibliotecă",
"Update the price list":"Actualizează lista de prețuri",
"Delete and copy":"Șterge și copiază",
"Do not delete, add":"Nu șterge, adaugă",
"Do not update":"Nu actualiza",
"For all":"Pentru toți",
"Overwrite":"Suprascrie",
"Copied":"Copiat",
"There is no such file":"Nu există acest fișier",
"Left unchanged":"Lăsat neschimbat",
"Yes":"Da",
"No":"Nu",
"Cancel":"Anulează",
"Update Settings":"Setări actualizare",
"Folder":"Dosar",
"Coincidence":"Coincidență",
"Overwritten":"Suprascris",
"Make folder":"Creează dosar",
"Changes":"Schimbări",
"Export to Layout":"Exportă în Layout",
"Specification":"Specificație",
"Parameters":"Parametri",
"Manual":"Manual",
"Open":"Deschide",
"Component options":"Opțiuni componentă",
"Activate button":"Buton activare",
"Draw mouldings":"Desenează profile",
"Select First point":"Selectează primul punct",
"Select Second point":"Selectează al doilea punct",
"Select Next point":"Selectează următorul punct",
"Panel options":"Opțiuni panou",
"Trim of panels":"Finisaj panouri",
"Dimensions of panels/niche":"Dimensiuni panouri/nise",
"Make module":"Creează modul",
"Explode module":"Explodează modul",
"Make accessory":"Creează accesoriu",
"Exploded View":"Vedere explodată",
"Update dimensions":"Actualizează dimensiuni",
"Delete hidden objects":"Șterge obiectele ascunse",
"Delete hidden":"Șterge ascunse",
"Fasteners":"Fixatori",
"Groove":"Canal",
"HDF":"HDF",
"Plinth":" ",
"Skirting":" ",
"Edge length 1":"Lungimea marginii 1",
"Edge length 2":"Lungimea marginii 2",
"Edge width 1":"Lățimea marginii 1",
"Edge width 2":"Lățimea marginii 2",
"Texture direction":"Direcția texturii",
"Panel cutout":"Decupare panou",
"Opening direction":"Direcția deschiderii",
"Showcase/grilles":"Vitrană/Grătare",
"Handle position":"Poziția mânerului",
"Reduce the length of the handle":"Redu lungimea mânerului",
"Turn the handle":"Întoarce mânerul",
"Increase the length of the handle":"Mărește lungimea mânerului",
"Layer enabled":"Strat activat",
"Gluing":"Склейка",
"The width of the material is less than the width of the panel.":"Ширина материала меньше ширины панели.",
"Change the direction of the texture and reduce the size?":"Schimbați direcția texturii și reduceți dimensiunea?",
"The size is larger than the maximum!":"Dimensiunea este mai mare decât maximul!",
"Numbering of Modules":"Numerotarea modulelor",
"by parameters":"după parametri",
"Press Tab to view components with attributes":"Apasă Tab pentru a vedea componentele cu atribute",
"Drawing of Panels with cutout":"Desenul panourilor cu decupaj",
"Resave for LayOut":"Re-salvare pentru LayOut",
"Hide in other scenes":"Ascunde în alte scene",
"Error! Repeat the position.":"Eroare! Repetă poziția.",
"Need to change materials again.":"Нужно заново перекрасить.",
"Details list":"Lista detaliilor",
"by materials":"pe materiale",
"by modules":"pe module",
"Panels":"Panouri",
"Specification of technic":"Specificație tehnică",
"Drawings":"Desene",
"carcass":"carcasă",
"chipboard":"CPB",
"Frontals":"Fațade",
"of upper base":" ",
"of high base":" ",
"of lower base":" ",
"of mezzanines":" ",
"of slats":" ",
"MDF":"MDF",
"MDF in veneer":"MDF",
"MDF in enamel":"MDF",
"MDF in plastic":"MDF",
"MDF in PVC film":"MDF",
"milling":"фр-ка",
"J_profile":"Profil J",
"Modern":"Модерн",
"the reverse side":"обр.стор.",
"White":"White",
"patina":" ",
"gloss":"lucios",
"matte":"mat",
"Order less than 1m2":"Comandă mai mică de 1m2",
"frontal":"Фасад",
"back":"spate",
"glass":"sticlă",
"painted":"vopsit",
"other":"altul",
"worktops":"Blaturi",
"worktop":"Blat",
"fartuks":"Panel 12 mm,",
"fartuk":"Panel 12 mm,",
"made of stone":" ",
"name":"nume",
"itemcode":"cod produs",
"product":"produs",
"title":"titlu",
"position":"poziție",
"length":"lungime",
"width":"lățime",
"count":"cantitate",
"unit":"unitate",
"thickness":"grosime",
"material":"material",
"Accessories":"Accesorii",
"Profil list":"Listă profile",
"Pipe list":"Listă țevi",
"Double click or drag to select objects.":"Dublu clic sau trage pentru a selecta obiecte.",
"Make a backup of the settings?":"Creează un backup al setărilor?",
"Edge banding":"Aplicare margine",
"Pasted strips":"Benzi lipite",
"Grooves":"Canale",
"Groove for the back wall":"Canal pentru peretele din spate",
"Holes":"Găuri",
"m":"m",
"mm":"mm",
"pc":"buc",
"sq.m.":"mp",
"cub.m.":"mc",
"w/o inst":"fără instalare",
"inst":"instalare",
"inst and con":"instalare și conectare",
"double-sided":"dublu-față",
"G":"G",
"Q":"Q",
"hole":"gaură",
"through":"trece",
"front":"față",
"flip":"întoarce",
"flank":"flanc",
"J-profile milling":"Frezare profil J",
"Count of all holes":"Număr total de găuri",
"Remove guides other than SUF":"Elimină ghidurile altele decât AR",
"Kitchen scenes":"Scene de bucătărie",
"Scene for carcass":"Scenă pentru carcase",
"Scene for carcass for current Scene":"Scenă pentru carcase pentru scena curentă",
"Scene for selection":"Scenă pentru selecție",
"Update Camera in Kitchen scenes":"Actualizează camera în scenele de bucătărie",
"Scenes for Modules":"Scene pentru module",
"Import components from folder":"Importă componente din dosar",
"On/Off observers":"Activare/Dezactivare observatori",
"White faces and color holes":"Fețe albe și găuri colorate",
"SUF Tools":"Instrumente",
"SUF Scenes":"Scene",
"New Scene":"Scenă nouă",
"Add Scene with name":"Adaugă scenă cu nume",
"Delete Scenes":"Șterge scene",
"after the current":"după scena curentă",
"to the end":"până la final",
"There are no modules in the model":"Nu există module în model",
"Apply":"START",
"Available in version ":"Disponibil în versiunea ",
" and above.":" și mai mare.",
"Pay via the website?":"Plătește prin site?",
"Available only with the purchase of a kitchen library":"Disponibil doar cu achiziționarea unei biblioteci de bucătărie",
"Wrong date set":"Dată setată greșit",
"If you need a license, then write to":"Dacă aveți nevoie de licență, scrieți la",
"Error code":"Cod eroare",
"Time":"Timp",
"Need to update the license":"Este necesar să actualizați licența",
"Update now":"Actualizează acum",
"Is the plugin activated":"Este pluginul activat",
"Press the activation button again":"Apăsați din nou butonul de activare",
"The plugin needs a license to work":"Pluginul necesită o licență pentru a funcționa",
"Until the end of the license is left":"Până la expirarea licenței rămân",
"Until the end of the license is left:":"Până la expirarea licenței rămân:",
"Update the license":"Actualizează licența",
"Download the new version":"Descarcă noua versiune",
"Download the cutting plugin":"Descarcă pluginul de tăiere",
"Download script for bazis":"Descarcă script pentru bazis",
"day":"zi",
"days":"zile",
"Enter email:":"Introduceți email:",
"Activation data has been sent":"Datele de activare au fost trimise",
"Wait for an email with instructions":"Așteptați un email cu instrucțiuni",
"if the letter has not arrived within an hour":"dacă emailul nu a sosit într-o oră",
"write to RigadaCo@gmail.com":"...",
"Open a website to pay for license renewal":"...",
"Incorrect email":"...",
"It is not possible to change the formula in the name":"Nu este posibil să schimbați formula din nume",
"Delete Formula":"Șterge formula",
"Export":"Exportă",
"to the program":"în program",
"Replace ":"Înlocuiește ",
"with":"cu",
"incompatible with Tip-on":"incompatibil cu Tip-on",
"with Tip-on. Install the handle":"cu Tip-on. Instalați mânerul",
"The width of the module should be:\n450, 500, 600, 700, 800 or 900 mm":"Lățimea modulului ar trebui să fie:\n450, 500, 600, 700, 800 sau 900 mm",
"Hinges":"Balamale",
"full overlay":"acoperire completă",
"partial overlay":"acoperire parțială",
"inset":"încălțat",
"screw-on":"cu șuruburi",
"Not available":"Indisponibil",
"The Components folder is missing in the selected folder":"Dosarul Componente lipsește din dosarul selectat",
"The Materials folder is missing in the selected folder":"Dosarul Materiale lipsește din dosarul selectat",
"The price folder is missing in the selected folder":"Dosarul Prețuri lipsește din dosarul selectat",
"New name":"Nume nou",
"The name contains the symbol #":"Numele conține simbolul #",
"The model has a component with the same name":"Modelul are un component cu același nume",
"The name must be unique":"Numele trebuie să fie unic",
"Try to purge unused components from the model":"Încearcă să elimini componentele neutilizate din model",
"The selection includes groups":"Selecția conține grupuri",
"Please select only components":"Selectează doar componente",
"Component names must not contain #":"Numele componentelor nu trebuie să conțină #",
"Do you want to rename it":"Vrei să-i schimbi numele",
"Component type":"Tip componentă",
"Image":"Imagine",
"Select folder":"Selectează folder",
"Do not save":"Nu salva",
"Zoom and Save":"Zoom și salvează",
"Save as is":"Salvează așa cum este",
"Component name":"Nume componentă",
"Select parameters":"Selectează parametrii",
"Available in version":"Disponibil în versiunea",
"and above.":"și mai nouă.",
"Pay via website?":"Plătești prin site?",
"Waiting for payment, will activate upon receipt.":"Se așteaptă plata, se va activa la confirmare.",
"Paid?":"Plătit?",
"Upper modules must be more than 500 mm above the floor":"Modulele superioare trebuie să fie la peste 500 mm deasupra podelei",
"Overhead units must be above Upper units from the floor":"Unitățile suspendate trebuie să fie deasupra modulelor superioare față de podea",
"Numbering type":"Tip numerotare",
"Continuous numbering":"Numerotare continuă",
"Sorting method":"Metodă de sortare",
"Module order":"Ordinea modulelor",
"General prefix":"Prefix general",
"Show general prefix":"Afișează prefixul general",
"Lower units prefix":"Prefix module inferioare",
"Upper units prefix":"Prefix module superioare",
"Upper from floor":"Înălțime module superioare de la podea",
"Overhead units prefix":"Prefix unități suspendate",
"Overhead from floor":"Înălțime unități suspendate de la podea",
"Save to":"Salvează în",
"Show code":"Afișează codul",
"Code before module":"Cod înaintea modulului",
"Code color":"Culoare cod",
"Code size":"Dimensiune cod",
"Height offset":"Decalaj pe înălțime",
"Starting number":"Număr de început",
"Newline instead of symbol":"Linie nouă în loc de simbol",
"In selection order":"În ordinea selecției",
"Number selected":"Numără selecția",
"All":"Toate",
"Current module code":"Codul modulului curent",
"From corner":"Din colț",
"Left to right":"De la stânga la dreapta",
"Clockwise":"În sensul acelor de ceas",
"Bottom to top":"De jos în sus",
"Top to bottom":"De sus în jos",
"Product code":"Cod produs",
"Everywhere":"Peste tot",
"Before module":"Înaintea modulului",
"Above module":"Deasupra modulului",
"All spaces":"Toate spațiile",
"First space":"Primul spațiu",
"Last space":"Ultimul spațiu",
"All dots":"Toate punctele",
"First dot":"Primul punct",
"Last dot":"Ultimul punct",
"No scenes created":"Nu au fost create scene",
"Only one scene exists":"Există doar o singură scenă",
"No settings files in the folder":"Nu există fișiere de setări în folder",
"Program version":"Versiunea programului",
"Bazis 11 and above":"Bazis 11 și mai nou",
"Bazis 8–10":"Bazis 8–10",
"Bazis version":"Versiune Bazis",
"Select folder to save settings":"Selectează folderul pentru salvarea setărilor",
"Select folder with settings":"Selectează folderul cu setări",
"General":"General",
"Drilling":"Găurire",
"Template":"Șablon",
"Slides":"Glisiere",
"Fittings":"Accesorii",
"Text":"Text",
"Countertops":"Blaturi",
"Backsplashes":"Plinte/Spate blaturi",
"Fronts":"Fațade",
"Confirm":"Confirmă",
"Profile name":"Nume profil",
"A profile with this name already exists!":"Există deja un profil cu acest nume!",
"Symbols | and / are not allowed":"Simbolurile | și / nu sunt permise",
"Select a Folder for screenshots and export to LayOut":"Selectează un folder pentru capturi și export în LayOut",
"Select folder with SUF library (Cancel — Use default folder)":"Selectează folderul cu biblioteca SUF (Anulează — Folosește folderul implicit)",
"Move library to new folder":"Mută biblioteca în folderul nou",
"Yes – Entire library will be moved to the selected folder":"Da – Biblioteca va fi mutată complet în folderul selectat",
"No – The selected folder will be used":"Nu – Va fi folosit folderul selectat",
"Move library to default folder":"Mută biblioteca în folderul implicit",
"Yes – The entire library will be moved to the folder":"Da – Biblioteca întreagă va fi mutată în folder",
"No – The default folder will be used":"Nu – Va fi folosit folderul implicit",
"Select folder with SUF settings (Cancel — Use default folder)":"Selectează folderul cu setările SUF (Anulează — Folosește folderul implicit)",
"Moving library files…":"Se mută fișierele bibliotecii…",
"Success":"Succes",
"Select logo file (Cancel — Use default)":"Selectează fișierul logo (Anulează — Folosește implicit)",
"Length":"Lungime",
"Save a copy of the project":"Salvează o copie a proiectului",
"Maximum module width":"Lățimea maximă a modulului",
"Increase maximum width":"Crește lățimea maximă",
"Selection contains chipboard fronts":"Selecția conține fațade din PAL",
"Apply milling and reset color":"Aplică frezare și resetează culoarea",
"Radius front cannot be made from chipboard":"Fațada rotunjită nu poate fi făcută din PAL",
"Do not change":"Nu modifica",
"Handle article number":"Cod articol mâner",
"Handle size":"Dimensiune mâner",
"Handle parameters":"Parametri mâner",
"Type":"Tip",
"Manufacturer":"Producător",
"recessed long":"încastrat lung",
"recessed short":"încastrat scurt",
"with holder long":"cu suport lung",
"with holder short":"cu suport scurt",
"white":" ",
"grey":"gri",
"black":"negru",
"(Blum, Austria)":"(Blum, Austria)",
"Side color":"Culoare laterală",
"Drawer parameters":"Parametri sertar",
"Select texture file":"Selectează fișier textură",
"Add to price list":"Adaugă în listă de prețuri",
"Frame":"Ramă",
"Frame color":"Culoare ramă",
"Change hinges":"Schimbă balamalele",
"Old name":"Nume vechi",
"Front parameters":"Parametri fațadă",
"Milling":"Frezare",
"Back side of fronts":"Spate fațadă",
"Front material":"Material fațadă",
"White + Stripe in front color":"Alb + Dungă în culoarea fațadei",
"Same as front color":"La fel ca fațada",
"Copy texture":"Copiază textura",
"By width":"Pe lățime",
"By height":"Pe înălțime",
"By depth":"Pe adâncime",
"Paint edge":"Colorează cantul",
"Change thickness":"Schimbă grosimea",
"Add glue to name":"Adaugă lipici în nume",
"By panel face":"După fața plăcii",
"Everywhere applicable":"Oriunde este aplicabil",
"Edge on parts":"Cant pe piese",
"Panel list is empty!":"Lista panourilor este goală!",
"Sheet length":"Lungime placă",
"Sheet width":"Lățime placă",
"Sheet trimming by length":"Tăiere placă pe lungime",
"Sheet trimming by width":"Tăiere placă pe lățime",
"Panel cutting":"Tăiere panouri",
"Sheet parameters":"Parametri placă",
"Panels that don't fit on the sheet":"Panouri care nu încap pe placă",
"Zoom in":"Mărește",
"Zoom out":"Micșorează",
"Number of sheets":"Număr de plăci",
"Number of panels":"Număr panouri",
"Panel rotated":"Panou rotit",
"General_view":"Vedere_generală",
"Cases":"Carcase",
"Drawer height must be at least 64 mm":"Înălțimea sertarului trebuie să fie cel puțin 64 mm",
"All values cannot be changed":"Toate valorile nu pot fi modificate",
"Distance must be at least 26 mm":"Distanța trebuie să fie de cel puțin 26 mm",
"Distance between panels must be at least 26 mm":"Distanța între panouri trebuie să fie de cel puțin 26 mm",
"Cutout length/radius exceeds part length!":"Lungimea/radiusul decupajului depășește lungimea piesei!",
"Cutout width exceeds part width!":"Lățimea decupajului depășește lățimea piesei!",
"Cutouts length/radius exceeds part length!":"Lungimea/radiusul decupajelor depășește lungimea piesei!",
"Cutouts width exceeds part width!":"Lățimea decupajelor depășește lățimea piesei!",
"No price file":"Fișier de prețuri inexistent",
"Delete database folder":"Șterge folderul bazei de date",
"and all its files":"și toate fișierele din el",
"Name database":"Nume bază de date",
"Add file to database":"Adaugă fișier în bază de date",
"Delete database":"Șterge baza de date",
"Name for production":"Nume pentru producție",
"Include in export":"Include în export",
"Previous value":"Valoare anterioară",
"Next value":"Valoare următoare",
"Search the database":"Caută în bază de date",
"New":"Nou",
"Folder name for new materials database":"Nume folder pentru baza de date materiale",
"Select Excel file":"Selectează fișier Excel",
"Column 1 - Article | Column 2 - Name":"Coloana 1 - Cod | Coloana 2 - Nume",
"From price list":"Din lista de prețuri",
"Materials in database":"Materiale în bază de date",
"Search by name or article...":"Caută după nume sau cod...",
"Materials table":"Tabel materiale",
"OCL plugin for cutting is not installed!":"Pluginul OCL pentru tăiere nu este instalat!",
"List of fronts":"Listă fațade",
"Material number":"Număr material",
"Order number":"Număr comandă",
"Parameters for Cutting3":"Parametri pentru Cutting3",
"Minimum drilling depth is 1 mm":"Adâncimea minimă de găurire este 1 mm",
"Specify the visible side":"Specifică partea vizibilă",
"Hover over the panel":"Treci cu mouse-ul peste panou",
"Drilling depth":"Adâncime găurire",
"Diameter":"Diametru",
"Color":"Culoare",
"Reset":"Resetează",
"Exit":"Ieșire",
"Select Components or Groups":"Selectează Componente sau Grupuri",
"Click on the guide line when it becomes solid":"Fă clic pe linia de ghidare când devine solidă",
"Hold Shift - symmetrical":"Ține apăsat Shift – simetric",
"Hold Ctrl - symmetrical":"Ține apăsat Ctrl – simetric",
"Delete fitting: Double-click on the fitting":"Șterge accesoriul: Dublu clic pe accesoriu",
"Fitting on the other side: Up arrow":"Accesoriu pe cealaltă parte: Săgeată sus",
"Number of fittings":"Număr accesorii",
"Left/Right arrows":"Săgeți stânga/dreapta",
"Set all to side: Down arrow":"Setează toate pe lateral: Săgeată jos",
"Delete drilling":"Șterge găurirea",
"Visible side":"Parte vizibilă",
"Panels without drilling":"Panouri fără găuriri",
"Drilling by template":"Găurire după șablon",
"Hardware drilling":"Găurire pentru accesorii",
"Separate hole":"Gaură separată",
"Fitting installation":"Montare accesorii",
"Symmetrical":"Simetric",
"From front edge":"De la marginea frontală",
"From back edge":"De la marginea din spate",
"Drill":"Găurește",
"Only selected":"Doar selectate",
"All panels":"Toate panourile",
"Hinge adjustment":"Ajustare balamale",
"In model":"În model",
"From selected":"Din selecție",
"Delete all holes":"Șterge toate găurile",
"Delete template holes":"Șterge găurile din șablon",
"Delete hardware holes":"Șterge găurile pentru accesorii",
"Delete separate holes":"Șterge găurile separate",
"Reset template settings in Parameters":"Resetează setările șablonului în Parametri",
"Resave template settings in Parameters":"Resalvează setările șablonului în Parametri",
"and restart the tool.":"și repornește unealta.",
"In Parameters under the Template tab":"În Parametri, fila Șablon",
"no rules specified for:":"nu există reguli definite pentru:",
"Settings":"Setări",
"On the panel":"Pe panou",
"There are holes on the other side within radius":"Există găuri pe cealaltă parte în raza specificată",
"Hardware":"Accesorii",
"Current fitting":"Accesoriu curent",
"Offset fitting by":"Decalează accesoriul cu",
"Change fitting to":"Schimbă accesoriul cu",
"Change depth":"Modifică adâncimea",
"Make through-hole":"Fă gaură completă",
"Half panel thickness":"Jumătate din grosimea panoului",
"Minimum distance 10 mm":"Distanța minimă 10 mm",
"Fastener position from edge":"Poziția prinderii față de margine",
"system32":"system32",
"Use Ctrl only for sections with drawers":"Folosește Ctrl doar pentru secțiuni cu sertare",
"Drawer installation type":"Tip montaj sertar",
"Drawer width":"Lățime sertar",
"Number across width":"Număr pe lățime",
"Drawer depth":"Adâncime sertar",
"Depth (if Fixed)":"Adâncime (dacă este fixă)",
"Rear clearance":"Spațiu în spate",
"Section height":"Înălțime secțiune",
"Height (if Fixed)":"Înălțime (dacă este fixă)",
"Front top clearance":"Spațiu sus față",
"Front bottom clearance":"Spațiu jos față",
"Front left clearance":"Spațiu stânga față",
"Front right clearance":"Spațiu dreapta față",
"Overlay":"Aplicație",
"Inset":"Încadrare",
"Niche width":"Lățime nișă",
"Module width":"Lățime modul",
"Maximum possible":"Maxim posibil",
"Fixed":"Fix",
"Between shelves":"Între rafturi",
"Module height":"Înălțime modul",
"Drawer section parameters":"Parametri secțiune sertar",
"Increase maximum module width?":"Crești lățimea maximă a modulului?",
"Aventos HF installation requires":"Montajul Aventos HF necesită",
"minimum 278 mm in depth!":"minim 278 mm adâncime!",
"Thickness":"Grosime",
"Top clearance":"Spațiu sus",
"Bottom clearance":"Spațiu jos",
"Left clearance":"Spațiu stânga",
"Right clearance":"Spațiu dreapta",
"Front width":"Lățime fațadă",
"Fixed width":"Lățime fixă",
"Horizontal position":"Poziție orizontală",
"Left":"Stânga",
"Right":"Dreapta",
"Bottom":"Jos",
"Top":"Sus",
"Front":"Față",
"Back":"Spate",
"Leftward":"Spre stânga",
"Rightward":"Spre dreapta",
"Upward":"În sus",
"Downward":"În jos",
"Center of niche":"Centru nișă",
"Placement parameters":"Parametri de plasare",
"Position of buttons":"Poziția butoanelor",
"Centered":"Centrat",
"below the list":"sub listă",
"Front height":"Înălțime fațadă",
"Niche height":"Înălțime nișă",
"Fixed height":"Înălțime fixă",
"Vertical position":"Poziție verticală",
"Front thickness":"Grosime fațadă",
"Fixed width must not exceed module width":"Lățimea fixă nu trebuie să depășească lățimea modulului",
"Fixed height must not exceed module height":"Înălțimea fixă nu trebuie să depășească înălțimea modulului",
"Change groove position from line":"Schimbă poziția canalului față de linie",
"Select another plane":"Selectează alt plan",
"Delete grooves":"Șterge canalele",
"From selection only":"Doar din selecție",
"Number of doors":"Număr uși",
"Number of shelves":"Număr rafturi",
"Number of drawers":"Număr sertare",
"Hold":"Ține apăsat",
"to install in niche":"pentru instalare în nișă",
"Press Tab to switch point by thickness":"Apasă Tab pentru a comuta punctul după grosime",
"Press Arrows to switch points along axes":"Folosește săgețile pentru a comuta punctele pe axe",
"Arrows move by panel thickness":"Săgețile mută după grosimea panoului",
"Press Tab to switch point by width":"Apasă Tab pentru a comuta punctul după lățime",
"Arrows move by edges":"Săgețile mută după margini",
"partes":"piese",
"parts":"părți",
"Internal module width is not divisible evenly":"Lățimea internă a modulului nu este divizibilă egal",
"Change module width":"Modifică lățimea modulului",
"Decrease by":"Scade cu",
"Increase by":"Crește cu",
"Leave unchanged":"Lasă neschimbat",
"Number of rails by height":"Număr șine pe înălțime",
"Rail section parameters":"Parametri secțiune șină",
"Edge thickness":"Grosime cant",
"no edge":"fără cant",
"Replace attachment points":"Înlocuiește punctele de prindere",
"By thickness":"După grosime",
"along X axis":"pe axa X",
"along Y axis":"pe axa Y",
"along Z axis":"pe axa Z",
"or":"sau",
"Another panel: Double-click LMB":"Alt panou: Dublu clic stânga",
"Add":"Adaugă",
"Exit: Esc or select tool":"Ieșire: Esc sau selectează unealtă",
"Trim panel":"Taie panoul",
"Edge offsets":"Decalaje cant",
"Thickness offset":"Decalaj grosime",
"Hide panel face":"Ascunde fața panoului",
"Remove edge":"Elimină cantul",
"Visible edges":"Canturi vizibile",
"Edge around":"Cant complet",
"Edge needed behind the front":"Cant necesar în spatele fațadei",
"Change front edges":"Schimbă canturile fațadei",
"Edging parameters":"Parametri cant",
"Edge needed on sides adjoining the back panel?":"Este necesar cant pe laturile adiacente panoului din spate?",
"Select edge from list":"Selectează cant din listă",
"File is already open":"Fișierul este deja deschis",
"Load error":"Eroare la încărcare",
"Loading complete":"Încărcare finalizată",
"Loading in progress":"Încărcare în curs",
"Attribute dialog":"Dialog atribute",
"Copy":"Copiază",
"Unit of measurement":"Unitate de măsură",
"Quantity (for pcs)":"Cantitate (bucăți)",
"Change":"Modifică",
"New accessory":"Accesoriu nou",
"Element":"Element",
"to Parent":"to Parent",
"Copy this attribute for pasting into other components":"Copy this attribute for pasting into other components",
"Copy this attribute to the parent component":"Copy this attribute to the parent component",
"Enter a dependency formula into this component":"Enter a dependency formula into this component",
"Delete this attribute":"Delete this attribute",
"Up":"Up",
"Add to model":"Add to model",
"Auto update":"Auto update",
"Panel sizes":"Panel sizes",
"Price per unit":"Price per unit",
"Follow the link":"Follow the link"
}
