window.ARTROCKET_LANG = 'RU';
window.translationDB = {
  "Петли": "Петли",
  "Навесы": "Навесы",
  "Подъемник": "Подъёмники",
  "Ящики": "Ящики",
  "kitchen": "кухня",
  "bathroom": "ванная",
  "drawer": "ящик",
  "Drawers": "Ящики",

  "MAIN": "ОСНОВНОЕ",
  "ADDITIONAL": "ДОПОЛНИЕЛЬНОЕ",
  "HANDLE": "РУЧКИ",
  "FRONTAL": "ФАСАДЫ",
  "APPLIANCES": "ТЕХНИКА",
  "SANITARY": "САНТЕХНИКА",


  "Rod – wardrobe": "Штанга – гардероб",
  "Cargo – kitchen": "Карго – кухня",
  "Column – kitchen": "Колонна – кухня",
  "Mechanisms – corner": "Механизмы – угол",
  "organizers –": "органайзеры –",
  "Dish racks –": "Сушки -",
  "Corner mechanisms –": "Угловые механизмы –",

  "wardrobe rail": "штанга для шкафа",
  "Round": "Круглая",
  "Oval": "Овальная",
  "Rectangular": "Прямоугольная",

  "Oven_BI": "Духовка_ВСТ",
  "Fridge_BI": "Холодильник_ВСТ",
  "Fridge_FR": "Холодильник_ОТД",
  "Wine fridge_BI": "Винный холодильник_ВСТ",
  "Hood_BI": "Вытяжка_ВСТ",
  "Hood_FR": "Вытяжка_ОТД",
  "Washing machine_FR": "Стиральная машина_ОТД",
  "Dishwasher_BI": "Посудомоечная машина_ВСТ",
  "Dishwasher_FR": "Посудомоечная машина_ОТД",
  "Microwave_BI": "Микроволновка_ВСТ",
  "Cooktop_BI": "Варочная панель_ВСТ",

  "Milling": "Фрезеровка",
  "Showcase": "Витрина",
  "Faucet": "Смеситель",
  "Sink": "Мойка",
  "Door": "Дверь",
  "Knob": "Кнопка",
  "Edge": "Кромка",
  "Reling": "Релинг",
  "Guides": "Направляющие",
  "Drawer": "Ящик",
  "Dish rack with upper support for plates and tray": "Сушка с верхним держателем для тарелок и поддоном",
  "Dish rack with tray": "Сушка с поддоном",
  "Pull-out dish rack": "Выдвижная сушка",
  "Pull-out basket": "Выдвижная корзина",
  "sink": "мойка",
  "support": "подставка",
  "dividers": "разделители",
  "organizer": "органайзер",
  "Narrow_profile": "Узкий профиль",
  "Wide_profile": "Широкий профиль",
  "Hidden hangers": "Скрытые навесы",
  "Visible hangers": "Видимые навесы",
  "Extendable mechanism": "Выдвижной механизм",
  "Anti-slip mat": "Противоскользящий коврик",
  "Round rod": "Круглая штанга",
  "Oval rod": "Овальная штанга",
  "Rectangular rod": "Прямоугольная штанга",
  "Column": "Колонна",
  "Bottle rack": "Бутылочница",
  "bottle rack": "бутылочница",
  "Cargo": "Карго",
  "cargo": "карго",
  "kitchen assistant": "кухонный помощник",
  "Dividers": "Разделители",
  "Organizer": "Органайзер",
  "Hinge": "Петля",
  "soft-close": "'плавное закрывание'",
  "dummy": "",
  "without": "без",
  "angled": "угловая",
  "refrigerator": "для холодиьника",
  "wide-angle": "широкоугольная",
  "slim-frame": "с тонкой рамкой",

 "✓ - Mâner-profil":                           "✓ - Профильная ручка",
  "✓ - Extinderea fațadei":                    "✓ - Расширение фасада",
  "✓ - Retragerea bazei":                      "✓ - Отступ основания",
  "✓ - Mâner-profil-LED":                      "✓ - Профильная LED-ручка",
  "✓ - Mâner-profil-L":                        "✓ - Профильная L-ручка",
  "✓ - Mâner-profil-C":                        "✓ - Профильная C-ручка",
  "⇄ - Retragere-profil-C":                    "⇄ - Отступ С-профиля",
  "✓ - PAL":                                   "✓ - ДСП",

  "Numerar":                                   "Наличные",
  "Rate pe 3 luni":                            "Рассрочка на 3 месяца",
  "Rate pe 6 luni":                            "Рассрочка на 6 месяцев",
  "Rate pe 12 luni":                           "Рассрочка на 12 месяцев",

  "Mâner margine":                             "Кромочная ручка",
  "Mâner buton":                               "Ручка-кнопка",
  "Mâner reling":                              "Рельсовая ручка",
  "Mâner arc":                                 "Дугообразная ручка",

  "Profil lat de vitrină":                     "Широкий профиль витрины",
  "Profil îngust de vitrină":                  "Узкий профиль витрины",
  "Profil Gola-GL, pentru modulele superioare":"Профиль Gola-GL для верхних модулей",
  "Profil Gola-L":                             "Профиль Gola-L",
  "Profil Gola-C":                             "Профиль Gola-C",
  "Profil Gola-SL-LED, pentru modulele superioare":"Профиль Gola-SL-LED для верхних модулей",
  "Profil Gola-C-V":                           "Профиль Gola-C-V",
  "Profil Gola-L-V":                           "Профиль Gola-L-V",

  "Organizator pentru tacâmuri":               "Органайзер для столовых приборов",
  "Cargo-sticlieră":                           "Бутылочница",
  "Cargo":                                     "Карго",
  "Sticlieră":                                 "Подставка для бутылок",
  "Asistent culinar":                          "Кухонный ассистент",
  "Uscător de vase cu tavă":                   "Сушилка для посуды с поддоном",
  "Uscător de vase cu suport superior pentru farfurii și tavă":  
                                               "Сушилка для посуды с верхней полкой для тарелок и поддона",
  "Mecanism extensibil de colț":               "Выдвижной уголок",
  "Set suspendatori ascunse":                  "Комплект скрытых держателей",
  "Set suspendatori vizibile":                 "Комплект видимых держателей",

  "front panel":                               "Лицевая панель",
  "sertarul interior":                         "Внутренний ящик",
  "suporturi":                                 "Кронштейны",
  "panoul frontal din aluminiu":               "Лицевая алюминиевая панель",
  "covoraș antiderapant pentru sertar":        "Противоскользящий коврик для ящика",

  "Împingător magn.":                          "Магнитный толкатель",
  "lung":                                      "Длинный",
  "scurt":                                     "Короткий",
  "încorporat":                                "Встроенный",

  "Coloană-organizator":                       "Колонна-органайзер",
  "Coloană-cargo":                             "Колонна-карго",
  "Coloană":                                   "Колонна",
  "Bară rotundă":                              "Круглый стержень",
  "Suport pentru bară rotundă":                "Кронштейн для круглого стержня",
  "Bară ovală":                                "Овальный стержень",
  "Suport pentru bară ovală":                  "Кронштейн для овального стержня",
  "Bară dreptunghiulară":                      "Прямоугольный стержень",
  "Suport pentru bară dreptunghiulară":        "Кронштейн для прямоугольного стержня",
  "Masă de călcat":                            "Гладильная доска",
  "Suport dublu pentru pantaloni":             "Двойная вешалка для брюк",
  "Suport pentru cămăși":                      "Вешалка для рубашек",
  "Suport pentru pantaloni":                   "Вешалка для брюк",
  "Raft pentru încălțăminte":                  "Полка для обуви",

  "Balamaua":                                  "Петля",
  "fără amortizor":                            "Без демпфера",
  "cu deschidere largă":                       "С широким углом открытия",
  "pentru cadru subțire":                      "Для тонкой рамки",
  "pentru profil cadru":                       "Для профильной рамки",
  "pentru frigider":                           "Для холодильника",
  "suprapunere":                               "Накладка",
  "cu închidere lentă":                        "С мягким закрытием",
  "încastrată":                                "Врезная",
  "cu amortizor":                              "С демпфером",
  "fără arc":                                  "Без пружины",
  "pentru push-to-open":                       "Для push-to-open",
  "pentru tip-on":                             "Для tip-on",
  "standard pentru gaz-lift":                  "Стандарт для газ-лифта",
  "unghiulară":                                "Угловая",
  "falsă":                                     "Фиктивная",

  "ghidaje ascunse sub sertar":                "Направляющие скрытые под ящиком",
  " complet":                                   " полный",
  " extensie":                                  " выдвижение",
  "sertar complex":                            "Система ящика",
  "cu amortizor":                              "С демпфером",
  "extensie completă":                         "Полное выдвижение",
  "două bare":                                 "Две перекладины",
  "interior":                                  "С внутренним ящиком",
  "deschidere prin apăsare":                   "Открытие нажатием",
  "cu fixator":                                "С фиксатором",
  "pentru încuietori":                         "Для замков",

  "Uscător extensibil":                        "Выдвижная сушилка",
  "Coș extensibil":                            "Выдвижная корзина",

  "Gas-lift":                                  "Газ-лифт",
  "Bandă LED":                                 "Светодиодная лента",
  "Capac difuzor pentru profil LED":           "Диффузионная крышка для профиля LED",
  "Sursă de alimentare LED":                   "LED-блок питания",
  "Buton integrat pentru iluminat LED":        "Встроенная кнопка для LED-подсветки",
  "Senzor pentru blat, pentru iluminat LED":   "Датчик для подсветки рабочей поверхности",
  "Senzor integrat pentru iluminat LED":       "Встроенный датчик для LED-подсветки",
  "Senzor colțar integrat pentru iluminat LED":"Угловой встроенный датчик LED-подсветки",
  "Senzor integrat de deschidere a fațadei, pentru iluminat LED":
                                               "Датчик открытия фасада для LED-подсветки",
  "Senzor de mișcare integrat, pentru iluminat LED":
                                               "Встроенный датчик движения для LED-подсветки",
  "Controler cu telecomandă pentru 4 zone, pentru iluminat LED":
                                               "Пульт на 4 зоны для LED-подсветки",
  "Controler cu telecomandă pentru 1 zonă, pentru iluminat LED":
                                               "Пульт на 1 зону для LED-подсветки",
  "Profil încastrat pentru bandă LED":        "Встроенный профиль для светодиодной ленты",

  "Frigider independent":                      "Отдельностоящий холодильник",
  "Plită incorporabilă":                       "Встраиваемая варочная панель",
  "Hotă incorporabilă":                        "Встраиваемая вытяжка",
  "Cuptor incorporabil":                       "Встраиваемый духовой шкаф",
  "Mașină de spălat vase inc.":                "Встраиваемая ПММ",
  "Frigider pentru vin inc.":                  "Встраиваемый винный холодильник",
  "Frigider incorporabil":                     "Встраиваемый холодильник",
  "Microundă încorporabilă":                   "Встраиваемая микроволновка",

  "Chiuvetă de bucătărie":                     "Кухонная мойка",
  "Baterie de bucătărie":                      "Кухонный смеситель",

  "Instalare electrocasnice si chiuvetă":      "Установка техники и мойки",
  "Profile metalice si componente suplimentare":"Металлические профили и доп. компоненты",
  "Servicii taiere si sudare metal":           "Услуги резки и сварки металла",
  "Tăiere și prelucrare paneluri HPL 12 mm":   "Резка и обработка HPL панелей 12 мм",
  "Tăiere și prelucrare paneluri PAL 8 mm":    "Резка и обработка ДСП панелей 8 мм",
  "Tăiere și prelucrare blat PAL 38 mm":       "Резка и обработка столешниц ДСП 38 мм",
  "Set suspendatori ascunse SAH 216 (Hettich, Germany)":
                                               "Комплект скрытых держателей SAH 216 (Hettich, Germany)",
  "Set suspendatori vizibile STRONG (Hafele, Germany)":
                                               "Комплект видимых держателей STRONG (Hafele, Germany)",
  "Componente suplimentare pentru feronerie":
                                               "Доп. компоненты для фурнитуры",
  "Set de profile pentru uși glisante":       "Набор профилей для раздвижных дверей",
  "SERVICII DE PRODUCȚIE":                     "ПРОИЗВОДСТВЕННЫЕ УСЛУГИ",

  "Specificație la contract":                 "Спецификация к контракту",
  "din":                                       "от",
  "Adresă:":                                   "Адрес:",

  "Setări":                                    "Настройки",
  "Actualizare":                               "Обновить",
  "Export în Google Sheets":                   "Экспорт в Google Sheets",
  "Export în Excel":                           "Экспорт в Excel",
  "Salvați specificația":                      "Сохранить спецификацию",
  "Contractul a fost semnat":                  "Контракт подписан",

  "Materiale":                                 "Материалы",
  "Feronerie":                                 "Фурнитура",
  "№":                                         "№",
  "Denumire":                                  "Наименование",
  "Cant.":                                     "Кол-во",
  "Preț":                                      "Цена",
  "Total":                                     "Итого",

  "Фото":                                      "Фото",
  "Описание":                                  "Описание",

  "Client:":                                   "Клиент:",
  "Număr:":                                    "Телефон:",
  "Produs:":                                   "Продукт:",
  "Adresă de livrare:":                        "Адрес доставки:",
  "Etaj:":                                     "Этаж:",
  "Lift de marfă":                             "Грузовой лифт:",
  "Distanță":                                  "Расстояние:",
  "Designer:":                                 "Дизайнер:",
  "Șeful departamentului de design:":          "Руководитель отдела дизайна:",

  "Termen de producere":                       "Срок производства",
  "zile lucrătoare":                           "рабочих дней",

  "Livrare și ridicare:":                      "Доставка и самовывоз:",
  "Sumă totală":                               "Общая сумма",

  "№ contractului":                            "№ контракта",
  "Data":                                      "Дата",
  "Client":                                    "Клиент",
  "Număr":                                     "Телефон",
  "Produs":                                    "Продукт",
  "Etaj":                                      "Этаж",
  "Lift de marfă":                             "Грузовой лифт",
  "Distanță":                                  "Расстояние",
  "Designer":                                  "Дизайнер",
  "Specificație pentru ofertă comercială":      "Спецификация для коммерческого предложения",
  "Salvați":                                   "Сохранить",
  "Avans":                                     "Аванс",

  "Fereastră":                                 "Окно",

  "Склейка": "Склейка панелей 18 мм",
  "фр-ка": "",
  "Panel ": "Панель ",
  "Worktop": "Столешница ",
  "Фасады": "Фасады",
  "Фасад": "Фасад",
  "МДФ в эмали": "МДФ",
  "Модерн": "Модерн",
  "Нестандартная ширина  920мм для столешницы 38мм": "Нестандартная ширина 920 мм для столешницы 38 мм",
  "Стекло": "Стекло",
  "Покраска металла в цвет": "Покраска металла в цвет",
  "мм": "мм",
  "Ножка": "Ножка",
  "обр.стор. Белая": "ЗС Белая",
  "обр.стор.": "ЗС"
};
