window.ARTROCKET_LANG = 'EN';
window.translationDB = {
  "Петли": "Hinges",
  "Навесы": "Wall brackets",
  "Подъемник": "Lift system",
  "Ящики": "Drawers",

  "✓ - Mâner-profil": "✓ - Profile handle",
  "✓ - Extinderea fațadei": "✓ - Front extension",
  "✓ - Retragerea bazei": "✓ - Base setback",
  "✓ - Mâner-profil-LED": "✓ - LED profile handle",
  "✓ - Mâner-profil-L": "✓ - L-profile handle",
  "✓ - Mâner-profil-C": "✓ - C-profile handle",
  "⇄ - Retragere-profil-C": "⇄ - C-profile setback",
  "✓ - PAL": "✓ - CPB",
  "ЛДСП": " ",

  "Numerar": "Cash",
  "Rate pe 3 luni": "3-month installment",
  "Rate pe 6 luni": "6-month installment",
  "Rate pe 12 luni": "12-month installment",

  "Mâner margine": "Edge handle",
  "Mâner buton": "Knob handle",
  "Mâner reling": "Reling handle",
  "Mâner arc": "Arc handle",
  "Profil lat de vitrină": "Wide showcase profile",
  "Profil îngust de vitrină": "Narrow showcase profile",
  "Profil Gola-GL, pentru modulele superioare": "Gola-GL profile for upper modules",
  "Profil Gola-L": "Gola-L profile",
  "Profil Gola-C": "Gola-C profile",
  "Profil Gola-SL-LED, pentru modulele superioare": "Gola-SL-LED profile for upper modules",
  "Profil Gola-C-V": "Gola-C-V profile",
  "Profil Gola-L-V": "Gola-L-V profile",

  "Organizator pentru tacâmuri": "Cutlery organizer",
  "Cargo-sticlieră": "Cargo bottle rack",
  "Cargo": "Cargo",
  "Sticlieră": "Bottle rack",
  "Asistent culinar": "Kitchen assistant",
  "Uscător de vase cu tavă": "Dish rack with tray",
  "Uscător de vase cu suport superior pentru farfurii și tavă": "Dish rack with upper support for plates and tray",
  "Mecanism extensibil de colț": "Corner pull-out mechanism",
  "Set suspendatori ascunse": "Hidden hanger set",
  "Set suspendatori vizibile": "Visible hanger set",

  "front panel": "aluminum front panel",
  "sertarul interior": "inner drawer",
  "suporturi": "brackets",
  "panoul frontal din aluminiu": "aluminum front panel",
  "covoraș antiderapant pentru sertar": "anti-slip drawer mat",

  "Împingător magn.": "Push magn.",
  "lung": "long",
  "scurt": "short",
  "încorporat": "integrated",

  "Coloană-organizator": "Organizer column",
  "Coloană-cargo": "Cargo column",
  "Coloană": "Column",
  "Bară rotundă": "Round rod",
  "Suport pentru bară rotundă": "Support for round rod",
  "Bară ovală": "Oval rod",
  "Suport pentru bară ovală": "Support for oval rod",
  "Bară dreptunghiulară": "Rectangular rod",
  "Suport pentru bară dreptunghiulară": "Support for rectangular rod",
  "Masă de călcat": "Ironing board",
  "Suport dublu pentru pantaloni": "Double pants rack",
  "Suport pentru cămăși": "Shirt holder",
  "Suport pentru pantaloni": "Pants rack",
  "Raft pentru încălțăminte": "Shoe rack",

  "Balamaua": "Hinge",
  "fără amortizor": "without damper",
  "cu deschidere largă": "wide opening hinge",
  "pentru cadru subțire": "thin frame hinge",
  "pentru profil cadru": "frame profile",
  "pentru frigider": "fridge",
  "suprapunere": "overlay",
  "cu închidere lentă": "with soft-close",
  "încastrată": "inset",
  "cu amortizor": "with damper",
  "fără arc": "without spring",
  "pentru push-to-open": "for push-to-open",
  "pentru tip-on": "for tip-on",
  "standard pentru gaz-lift": "standard for gas-lift",
  "unghiulară": "angled",
  "falsă":"dummy",

  "ghidaje ascunse sub sertar": "undermount runners",
  " complet": " full",
  " extensie": " extension",
  "sertar complex": "drawer system",
  "cu amortizor": "with soft-close",
  "extensie completă": "full extension",
  "două bare": "double railing",
  "deschidere prin apăsare": "push-to-open",
  "cu fixator": "with catch",
  "pentru încuietori": "for locking system",
  
  "Uscător extensibil": "Pull-out dish rack",
  "Coș extensibil": "Pull-out basket",

  "Set suspendatori ascunse": "Hidden hanger set",
  "Set suspendatori vizibile": "Visible hanger set",

  "Suport pentru bară rotundă": "Support for round rod",
  "Suport pentru bară ovală": "Support for oval rod",
  "Suport pentru bară dreptunghiulară": "Support for rectangular rod",
  "Masă de călcat": "Ironing board",
  "Suport dublu pentru pantaloni": "Double pants rack",
  "Suport pentru cămăși": "Shirt holder",
  "Suport pentru pantaloni": "Pants rack",
  "Raft pentru încălțăminte": "Shoe rack",

  "Gas-lift": "Gas lift",

  "Bandă LED": "LED strip",
  "Capac difuzor pentru profil LED": "Diffuser cover for LED profile",
  "Sursă de alimentare LED": "LED power supply",
  "Buton integrat pentru iluminat LED": "Integrated button for LED lighting",
  "Senzor pentru blat, pentru iluminat LED": "Countertop sensor for LED lighting",
  "Senzor integrat pentru iluminat LED": "Integrated sensor for LED lighting",
  "Senzor colțar integrat pentru iluminat LED": "Corner sensor for LED lighting",
  "Senzor integrat de deschidere a fațadei, pentru iluminat LED": "Integrated door opening sensor for LED lighting",
  "Senzor de mișcare integrat, pentru iluminat LED": "Integrated motion sensor for LED lighting",
  "Controler cu telecomandă pentru 4 zone, pentru iluminat LED": "Remote controller for 4 zones, for LED lighting",
  "Controler cu telecomandă pentru 1 zonă, pentru iluminat LED": "Remote controller for 1 zone, for LED lighting",
  "Profil încastrat pentru bandă LED": "Recessed profile for LED strip",

  "Frigider independent": "Freestanding fridge",
  "Plită incorporabilă": "Built-in cooktop",
  "Hotă incorporabilă": "Built-in hood",
  "Cuptor incorporabil": "Built-in oven",
  "Mașină de spălat vase inc.": "Built-in dishwasher",
  "Frigider pentru vin inc.": "Built-in wine fridge",
  "Frigider incorporabil": "Built-in fridge",
  "Microundă încorporabilă": "Built-in microwave",

  "Chiuvetă de bucătărie": "Kitchen sink",
  "Baterie de bucătărie": "Kitchen faucet",

  "Instalare electrocasnice si chiuvetă": "Installation of appliances and sink",
  "Profile metalice si componente suplimentare": "Metal profiles and additional components",
  "Servicii taiere si sudare metal": "Metal cutting and welding services",
  "Tăiere și prelucrare paneluri HPL 12 mm": "Cutting and processing HPL panels 12 mm",
  "Tăiere și prelucrare paneluri PAL 8 mm": "Cutting and processing chipboard panels 8 mm",
  "Tăiere și prelucrare blat PAL 38 mm": "Cutting and processing chipboard countertops 38 mm",
  "Set suspendatori ascunse SAH 216 (Hettich, Germany)": "Set of hidden hangers SAH 216 (Hettich, Germany)",
  "Set suspendatori vizibile STRONG (Hafele, Germany)": "Set of visible hangers STRONG (Hafele, Germany)",
  "Componente suplimentare pentru feronerie": "Additional components for fittings",
  "Set de profile pentru uși glisante": "Set of profiles for sliding doors",
  "SERVICII DE PRODUCȚIE": "PRODUCTION SERVICES",

"Specificație la contract": "Specification for contract",
"Adresă:": "Address:",

"Setări": "Settings",
"Actualizare": "Update",
"Export în Google Sheets": "Export to Google Sheets",
"Export în Excel": "Export to Excel",
"Salvați specificația": "Save specification",
"Contractul a fost semnat": "Contract has been signed",

"Materiale": "Materials",
"Feronerie": "Hardware",
"№": "No.",
"Denumire": "Name",
"Cant.": "Qty.",
"Preț": "Price",
"Total": "Total",

"Фото": "Photo",
"Описание": "Description",

"Client:": "Client:",
"Număr:": "Phone number:",
"Produs:": "Product:",
"Adresă de livrare:": "Delivery address:",
"Etaj:": "Floor:",
"Lift de marfă": "Freight elevator:",
"Distanță:": "Distance:",
"Designer:": "Designer:",
"Șeful departamentului de design:": "Head of Design Department:",

"Termen de producere": "Production lead time",
"zile lucrătoare": "working days",

"Livrare și ridicare:": "Delivery and pick-up:",
"Sumă totală": "Total amount",

"№ contractului": "Contract No.",
"Data": "Date",
"Client": "Client",
"Număr": "Phone number",
"Produs": "Product",
"Etaj": "Floor",
"Lift de marfă": "Freight elevator",
"Distanță": "Distance",
"Designer": "Designer",
"Specificație pentru ofertă comercială": "Specification for commercial offer",
"Salvați": "Save",
"Avans": "Advance",

"Нестандартная ширина  920мм для столешницы 38мм": "Non-standard 920mm width for 38mm worktop",
"Покраска металла в цвет": "Metal painting in color",
"Еврозапил": "Eurocut connection for worktops",
"Склейка": "Panel 18 mm  gluing",
"PAL": "CPB",
"Blat": "Worktop",
"Profile de perete": "Wall profiles",
"Ușă":"Door",
"Fereastră":"Window",

 "✓ - Скос": "✓ - Chamfer",
 "✓ - Радиус внешний": "✓ - Outer radius",
 "✓ - Радиус внутренний": "✓ - Inner radius",
 "✓ - Угол": "✓ - Corner",

  "Нет": "No",
  "Да": "Yes",
  "Есть": "Present",
  "Угол": "Corner",
  "По длине": "By length",
  "По ширине": "By width",
  "Не вращать": "Do not rotate",
  "Вращать": "Rotate",
  "Фасад": "Front",
  "Каркас": "Carcass",
  "Задняя_стенка": "Back panel",
  "Стекло": "Glass",
  "Фурнитура": "Hardware",
  "Ручка": "Handle",
  "Петля": "Hinge",
  "Ящик": "Drawer",
  "Корзина": "Basket",
  "Навес": "Hanging support",
  "Опора": "Leg",
  "Сушка": "Dish rack",
  "Подъемник": "Lift system",
  "Полкодержатель": "Shelf support",
  "Металл": "Metal",
  "1_Фасад": "1_Front",
  "1_Фасад_ящика": "1_Drawer front",
  "2_Стекло": "2_Glass",
  "3_Каркас": "3_Carcass",
  "3_Каркас_ящика": "3_Drawer carcass",
  "4_Задняя_стенка": "4_Back panel",
  "4_Металл": "4_Metal",
  "9_Фурнитура": "9_Hardware",
  "кв.м": "sq.m",
  "пог.м по длине": "lin.m (length)",
  "пог.м по ширине": "lin.m (width)",
  "периметр": "Perimeter",
  "количество": "Quantity",
  "куб.м": "cu.m",
  "В цвет лицевой": "Match front color",
  "Слева": "Left",
  "Справа": "Right",
  "По центру": "Center",
  "Материал панели": "Panel material",
  "Материал кромки": "Edge material",
  "Сзади": "Back",
  "Спереди": "Front",
  "Снизу": "Bottom",
  "Сверху": "Top",
  "Белая": "White",
  "Белая + Полоса в цвет лицевой": "White + Band in front color",
  "Авто": "Auto",
  "Вручную": "Manual",
  "Накладные": "Overlay",
  "Полунакладные": "Half overlay",
  "Вкладные": "Inset",
  "крест. саморезы": "crosshead screws",
  "крест. евровинты": "crosshead euro screws",
  "прямая саморезы": "straight screws",
  "прямая евровинты": "straight euro screws",
  "без присадки": "without drilling",
  "на саморезы": "on screws",
  "Налево": "To the left",
  "Направо": "To the right",
  "Вниз": "Down",
  "Вверх": "Up",
  "Показать/Скрыть": "Show/Hide",
  "Фасад_Modern": "Front_Modern",
  "Радиус наружний": "Outer radius",
  "Радиус внутренний": "Inner radius",
  "Скос": "Chamfer",
  "Накладное": "Overlay",
  "Вкладное": "Inset",
  "В Паз": "Into groove",
  "Торец панели": "Panel edge",
  "Панель": "Panel",
  "Планки": "Strips",
  "Панель + Планки": "Panel + Strips",
  "Планка": "Strip",
  "Накладная": "Overlay",
  "Вкладная": "Inset",
  "Слева и справа": "Left and right",
  "Только слева": "Left only",
  "Только справа": "Right only",
  "В четверть": "Rabbeted",
  "Как есть": "As is",
  "Сместить": "Offset",
  "Скрыть": "Hide",
  "Горизонтально": "Horizontal",
  "Вертикально": "Vertical",
  "Ножки": "Feet",
  "Спереди и Сзади": "Front and back",
  "Спереди и Ножки": "Front and feet",
  "Накладная слева": "Overlay left",
  "Накладная справа": "Overlay right",
  "С бекингом": "With backing",
  "Двухсторонняя": "Double-sided",
  "Прямая": "Straight",
  "Радиус": "Radius",
  "ПВХ": "PVC",
  "Планка торцевая": "End strip",
  "Планка соединительная": "Connecting strip",
  "Стыковочная угловая": "Corner joint strip",
  "Еврозапил": "Eurocut",
  "Завал": "Bevel",
  "Толщина панелей": "Panel thickness",
  "Толщина фасадов": "Front thickness",
  "Произвольная": "Custom",
  "Слева и Справа": "Left and Right",
  "Витрина": "Showcase",
  "Решетка4": "Grid4",
  "Решетка6": "Grid6",
  "Решетка8": "Grid8",
  "Серебро": "Silver",
  "Шампань": "Champagne",
  "Золото": "Gold",
  "Белый": "White",
  "Черный": "Black",
  "фр-ка": "",
  "Panel ": "Panel ",
  "Worktop": "Worktop",
  "Фасады": "Fronts",
  "Фасад": "Front",
  "МДФ в эмали":"MDF",
  "Модерн": "Modern",
  "Стекло": "Glass",
  "шт": "pcs",
  
  "Не менять": "Do not change",
  "Текущий": "Current",
  "0.6 мм": "0.6 mm",
  "1 мм": "1 mm",
  "2 мм": "2 mm",
  "м": "m",
  "мм": "mm",
  "Ножка": "Leg",
  "обр.стор. Белая": "RS White",
  "обр.стор.": "RS",

  "și": "and",
  "ridicare": "pickup",
  "Adresă de": "Address"
};