window.ARTROCKET_LANG = 'RO';
window.translationDB = {
    "Петли": "Balamale",
    "Навесы": "Suspendatori",
    "Подъемник": "Ridicatoare",
    "Ящики": "Sertare",

    "MAIN": "PRINCIPAL",
    "ADDITIONAL": "SUPLIMENTAR",
    "HANDLE": "MÂNER",
    "FRONTAL": "FRONT",
    "APPLIANCES": "ELECTROCASNICE",
    "SANITARY": "SANITARE",
    "Rod – wardrobe": "Bară – garderoba",
    "Cargo – kitchen": "Cargo – bucătărie",
    "Column – kitchen": "Coloane – bucătărie",
    "Sink – kitchen": "Chiuvetă – bucătărie",
    "Faucet – bathroom": "Baterie – baie",
    "Faucet – kitchen": "Baterie – bucătărie",
    "Corner mechanisms – kitchen": "Mecanisme de colț – bucătărie",
    "Drawer organizers – kitchen": "Organizatoare pentru sertare – bucătărie",
    "Dish racks – kitchen": "Uscătoare – bucătărie",
    "Oven_BI": "Cuptor_INC",
    "Fridge_BI": "Frigider_INC",
    "Fridge_FR": "Frigider_IND",
    "Wine fridge_BI": "Frigider_vin_INC",
    "Hood_BI": "Hotă_INC",
    "Hood_FR": "Hotă_IND",
    "Washing machine_FR": "Mașină_rufe_IND",
    "Dishwasher_BI": "Mașină_vase_INC",
    "Dishwasher_FR": "Mașină_vase_IND",
    "Microwave_BI": "Microunde_INC",
    "Cooktop_BI": "Plită_INC",
    "Milling": "Frezare",
    "Showcase": "Vitrina",
    "Faucet": "Baterie",
    "Sink": "Chiuvetă",
    "Knob": "Buton",
    "Edge": "Cant",
    "Reling": "Reling",

    "Guides": "Ghidaje",
    "Drawer": "Sertar",
    "Hinge": "Balama",
    "handle": "mâner",
    "Dish rack with upper support for plates and tray": "Uscător de vase cu suport superior pentru farfurii și tavă",
    "Dish rack with tray": "Uscător de vase cu tavă",
    "Pull-out dish rack": "Uscător extensibil",
    "Pull-out basket": "Coș extensibil",
    "sink": "chiuveta",
    "support": "suport",
    "dividers": "separatoare",
    "organizer": "organizator",
    "Narrow_profile": "Profil_îngust",
    "Wide_profile": "Profil_lat",
    "Hidden hangers": "Suspendatoare ascunse",
    "Visible hangers": "Suspendatoare vizibile",
    "Extendable mechanism": "Mecanism extensibil",
    "Anti-slip mat": "Covoraș antiderapant",
    "Round rod": "Bară rotundă",
    "Oval rod": "Bară ovală",
    "Rectangular rod": "Bară dreptunghiulară",
    "Column": "Coloană",
    "Bottle rack": "Sticlieră",
    "bottle rack": "sticlieră",
    "Cargo": "Cargo",
    "kitchen assistant": "asistent culinar",
    "Dividers": "Separatoare",
    "Organizer": "Organizator",
    "Нестандартная ширина  920мм для столешницы 38мм": "Non-standard 920mm width for 38mm worktop",

    "Door": "Ușă",
    "Window": "Fereastră",

"Склейка": "Lipire panouri 18 mm",
  "фр-ка": "",
  "Panel ": "Panou ",
  "Worktop": "Blat de lucru ",
  "Фасады": "Fațade",
  "Фасад": "Fațadă",
  "МДФ в эмали": "MDF vopsit",
  "Модерн": "Modern",
  "Нестандартная ширина  920мм для столешницы 38мм": "Lățime nestandard 920 mm pentru blat 38 mm",
  "Стекло": "Sticlă",
  "Покраска металла в цвет": "Vopsire metal în culoare",
  "мм": "mm",
  "Ножка": "Picior",
  "обр.стор. Белая": "Verso Alb",
  "обр.стор.": "Verso",
  "complex drawer, with soft-close, full extension": "sertar complex, cu amortizare, extensie totală",
  "two rails": "două relinguri",
  "Margine": "Cant",
  "Cutlery tray": "Tavă pentru tacâmuri",
  "Hinge": "Balama",
  "Mounting plate": "Placă de montaj",
  "overlay, soft-close": "aplicată, cu amortizare",
  "Front aluminum panel for internal drawer": "Panou frontal din aluminiu pentru sertar interior",
  "Holders for front aluminum panel for internal drawer": "Suporturi pentru panoul frontal din aluminiu al sertarului interior",
  "Pull-out dish drainer": "Uscător de vase extractibil",
  "Bottle Rack": "Suport pentru sticle",
  "Culinary Assistant": "Asistent culinar",
  "inset with soft-close": "încastrată, cu amortizare",
  "Corner pull-out mechanism": "Mecanism de colț extractibil",
  "dummy": "fals",
  "overlay": "aplicată",
  "lift-mechanism": "mecanism de ridicare",
  "opening by push": "deschidere prin apăsare",
  "concealed undermount slides": "glisiere ascunse sub montaj",
  "full extension": "extensie totală",
  "with catch": "cu fixare",

  "Frontals": "Fațade",
  "MDF": "MDF",
  "CPB": "PAL",
  "HDF": "HDF",
  "Profile": "Profil",
  "Milling": "Frezare",
  "Showcase": "Vitrină",
  "Faucet": "Baterie",
  "Sink": "Chiuvetă",
  "Knob": "Buton",
  "Reling": "Reling",
  "Guides": "Glisiere",
  "Drawer": "Sertar",
  "Dish rack with upper support for plates and tray": "Uscător cu suport superior pentru farfurii și tavă",
  "Dish rack with tray": "Uscător cu tavă",
  "Pull-out dish rack": "Uscător extractibil",
  "Pull-out basket": "Coș extractibil",
  "sink": "chiuvetă",
  "support": "suport",
  "dividers": "separatoare",
  "organizer": "organizator",
  "Narrow_profile": "Profil îngust",
  "Wide_profile": "Profil lat",
  "Hidden hangers": "Suporturi ascunse",
  "Visible hangers": "Suporturi vizibile",
  "Extendable mechanism": "Mecanism extensibil",
  "Anti-slip mat": "Covoraș antiderapant",
  "Round rod": "Bară rotundă",
  "Oval rod": "Bară ovală",
  "Rectangular rod": "Bară dreptunghiulară",
  "Column": "Coloană",
  "Bottle rack": "Suport pentru sticle",
  "bottle rack": "suport pentru sticle",
  "Cargo": "Cargo",
  "cargo": "cargo",
  "kitchen assistant": "asistent de bucătărie",
  "Dividers": "Separatoare",
  "Organizer": "Organizator",

  "Freestanding Cooker Hood": "Hotă de bucătărie independentă",
  "Built-in Cooker Hood": "Hotă de bucătărie încorporată",
  "Cooktop": "Plită",
  "Built-in oven": "Cuptor încorporat",
  "Built-in microwave": "Cuptor microunde încorporat",
  "Built-in dishwasher": "Mașină de spălat vase încorporată",
  "Built-in fridge": "Frigider încorporat",
  "Freestanding refrigerator": "Frigider independent",
  "Built-in wine cooler": "Răcitor de vin încorporat",

  "Drying machine": "Mașină de uscat rufe",
  "Washing machine": "Mașină de spălat rufe",
  "Air Conditioner": "Aer condiționat",
  "TV": "Televizor",

    "Нет": "Nu",
    "Да": "Da",
    "Есть": "Este",
    "Угол": "Colț",
    "По длине": "Pe lungime",
    "По ширине": "Pe lățime",
    "Не вращать": "Nu roti",
    "Вращать": "Rotește",
    "Фасад": "Fațadă",
    "Каркас": "Corp",
    "Задняя_стенка": "Spate",
    "Стекло": "Sticlă",
    "Фурнитура": "Feronerie",
    "Ручка": "Mâner",
    "Петля": "Balamale",
    "Ящик": "Sertar",
    "Корзина": "Coș",
    "Навес": "Suport de agățare",
    "Опора": "Picior",
    "Сушка": "Uscător",
    "Полкодержатель": "Suport poliță",
    "Металл": "Metal",
    "1_Фасад": "1_Fațadă",
    "1_Фасад_ящика": "1_Fațadă sertar",
    "2_Стекло": "2_Sticlă",
    "3_Каркас": "3_Corp",
    "3_Каркас_ящика": "3_Corp sertar",
    "4_Задняя_стенка": "4_Spate",
    "4_Металл": "4_Metal",
    "9_Фурнитура": "9_Feronerie",
    "кв.м": "m2",
    "пог.м по длине": "ml pe lungime",
    "пог.м по ширине": "ml pe lățime",
    "периметр": "Perimetru",
    "количество": "Cantitate",
    "куб.м": "m3",
    "В цвет лицевой": "În culoarea fațadei",
    "Слева": "Stânga",
    "Справа": "Dreapta",
    "По центру": "Centru",
    "Материал панели": "Materialul panoului",
    "Материал кромки": "Materialul cantului",
    "Сзади": "În spate",
    "Спереди": "În față",
    "Снизу": "Jos",
    "Сверху": "Sus",
    "шт": "buc",
    "м": "m",
    "Не менять": "Nu schimba",
    "Текущий": "Curent",
    "0.6 мм": "0.6 mm",
    "1 мм": "1 mm",
    "2 мм": "2 mm",
    "Белая": "Alb",
    "Белая + Полоса в цвет лицевой": "Albă + Bandă în culoarea fațadei",
    "Авто": "Auto",
    "Вручную": "Manual",
    "Накладные": "Aplicate",
    "Полунакладные": "Parțial aplicate",
    "Вкладные": "Încorporate",
    "крест. саморезы": "șuruburi tip cruce",
    "крест. евровинты": "eurosuruburi tip cruce",
    "прямая саморезы": "șuruburi drepte",
    "прямая евровинты": "eurosuruburi drepte",
    "без присадки": "fără găuri de montaj",
    "на саморезы": "pe șuruburi",
    "Налево": "La stânga",
    "Направо": "La dreapta",
    "Вниз": "În jos",
    "Вверх": "În sus",
    "Показать/Скрыть": "Arată/Ascunde",
    "Фасад_Modern": "Fațadă_Modern",
    "Радиус наружний": "Rază exterioară",
    "Радиус внутренний": "Rază interioară",
    "Скос": "Teșire",
    "Накладное": "Aplicat",
    "Вкладное": "Încorporat",
    "В Паз": "În canal",
    "Торец панели": "Capăt panou",
    "Панель": "Panou",
    "Планки": "Lamele",
    "Панель + Планки": "Panou + Lamele",
    "Планка": "Plintă",
    "Накладная": "Aplicată",
    "Вкладная": "Încorporată",
    "Слева и справа": "Stânga și dreapta",
    "Только слева": "Doar la stânga",
    "Только справа": "Doar la dreapta",
    "В четверть": "În cep",
    "Как есть": "Așa cum este",
    "Сместить": "Deplasare",
    "Скрыть": "Ascunde",
    "Горизонтально": "Orizontal",
    "Вертикально": "Vertical",
    "Ножки": "Picioare",
    "Спереди и Сзади": "În față și în spate",
    "Спереди и Ножки": "În față și picioare",
    "Накладная слева": "Aplicată pe stânga",
    "Накладная справа": "Aplicată pe dreapta",
    "С бекингом": "Cu backing",
    "Двухсторонняя": "Bilaterală",
    "Прямая": "Dreaptă",
    "Радиус": "Rază",
    "ПВХ": "PVC",
    "Планка торцевая": "Plintă de capăt",
    "Планка соединительная": "Plintă de îmbinare",
    "Стыковочная угловая": "Plintă colț de îmbinare",
    "Еврозапил": "Eurocut",
    "Завал": "Înclinare",
    "Толщина панелей": "Grosimea panourilor",
    "Толщина фасадов": "Grosimea fațadelor",
    "Произвольная": "Personalizată",
    "Слева и Справа": "Stânga și Dreapta",
    "Витрина": "Vitrină",
    "Решетка4": "Grilaj4",
    "Решетка6": "Grilaj6",
    "Решетка8": "Grilaj8",
    "Серебро": "Argintiu",
    "Шампань": "Șampanie",
    "Золото": "Auriu",
    "Белый": "Alb",
    "Черный": "Negru",
    "Склейка": "Lipire paneluri 18 mm",
    "фр-ка": "",
    "Panel ": "Panel ",
    "Worktop": "Blat ",
    "Фасады": "Fațade",
    "Фасад": "Fațadă",
    "МДФ в эмали": "MDF",
    "Модерн": "Modern",
  
    "Стекло": "Sticlă",
    "Покраска металла в цвет": "Vopsirea metalului în culoare",
    "мм": "mm",
    "Ножка": "Picior",
    "обр.стор. Белая": "RS White",
    "обр.стор.": "RS"
};